// Validating benchmarks:
// ***** BenchmarkRunner: Start   *****
// ***** Found 7 benchmark(s) in total *****
// ***** Building 1 exe(s) in Parallel: Start   *****
// start dotnet restore  /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4
// command took 2,06s and exited with 0
// start dotnet build -c Release  --no-restore /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4
// command took 3,22s and exited with 0
// ***** Done, took 00:00:05 (5.5 sec)   *****
// Found 7 benchmarks:
//   Array2AccessMethods.ForCacheArray: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
//   Array2AccessMethods.For: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
//   Array2AccessMethods.ForEach: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
//   Array2AccessMethods.LinqAggregate: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
//   Array2AccessMethods.LinqSum: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
//   Array2AccessMethods.LinqAll: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
//   Array2AccessMethods.LinqAny: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)

Setup power plan (GUID: 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c FriendlyName: High performance)// **************************
// Benchmark: Array2AccessMethods.ForCacheArray: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
// *** Execute ***
// Launch: 1 / 1
// Execute: dotnet "804ac9de-f76e-4442-9efe-0f0a4d318be4.dll" --benchmarkName "CSharpBenchmarks.Array2AccessMethods.ForCacheArray" --job "Jit=RyuJit, Platform=X64, Server=True" --benchmarkId 0 in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\bin\Release\netcoreapp2.2
// BeforeAnythingElse

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotSupportedException: Collection was of a fixed size.
   at CSharpBenchmarks.CollectionAccessMethods`1..ctor(T data) in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\Benchmarks\CollectionAccessMethods.cs:line 18
   at BenchmarkDotNet.Autogenerated.Runnable_0..ctor() in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\804ac9de-f76e-4442-9efe-0f0a4d318be4.notcs:line 187
   at BenchmarkDotNet.Autogenerated.Runnable_0.Run(IHost host, String benchmarkName) in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\804ac9de-f76e-4442-9efe-0f0a4d318be4.notcs:line 133
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\804ac9de-f76e-4442-9efe-0f0a4d318be4.notcs:line 54
// AfterAll
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!


// **************************
// Benchmark: Array2AccessMethods.For: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
// *** Execute ***
// Launch: 1 / 1
// Execute: dotnet "804ac9de-f76e-4442-9efe-0f0a4d318be4.dll" --benchmarkName "CSharpBenchmarks.Array2AccessMethods.For" --job "Jit=RyuJit, Platform=X64, Server=True" --benchmarkId 1 in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\bin\Release\netcoreapp2.2
// BeforeAnythingElse

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotSupportedException: Collection was of a fixed size.
   at CSharpBenchmarks.CollectionAccessMethods`1..ctor(T data) in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\Benchmarks\CollectionAccessMethods.cs:line 18
   at BenchmarkDotNet.Autogenerated.Runnable_1..ctor() in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\804ac9de-f76e-4442-9efe-0f0a4d318be4.notcs:line 833
   at BenchmarkDotNet.Autogenerated.Runnable_1.Run(IHost host, String benchmarkName) in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\804ac9de-f76e-4442-9efe-0f0a4d318be4.notcs:line 779
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\804ac9de-f76e-4442-9efe-0f0a4d318be4.notcs:line 54
// AfterAll
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!


// **************************
// Benchmark: Array2AccessMethods.ForEach: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
// *** Execute ***
// Launch: 1 / 1
// Execute: dotnet "804ac9de-f76e-4442-9efe-0f0a4d318be4.dll" --benchmarkName "CSharpBenchmarks.Array2AccessMethods.ForEach" --job "Jit=RyuJit, Platform=X64, Server=True" --benchmarkId 2 in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\bin\Release\netcoreapp2.2
// BeforeAnythingElse

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotSupportedException: Collection was of a fixed size.
   at CSharpBenchmarks.CollectionAccessMethods`1..ctor(T data) in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\Benchmarks\CollectionAccessMethods.cs:line 18
   at BenchmarkDotNet.Autogenerated.Runnable_2..ctor() in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\804ac9de-f76e-4442-9efe-0f0a4d318be4.notcs:line 1479
   at BenchmarkDotNet.Autogenerated.Runnable_2.Run(IHost host, String benchmarkName) in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\804ac9de-f76e-4442-9efe-0f0a4d318be4.notcs:line 1425
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\804ac9de-f76e-4442-9efe-0f0a4d318be4.notcs:line 54
// AfterAll
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!


// **************************
// Benchmark: Array2AccessMethods.LinqAggregate: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
// *** Execute ***
// Launch: 1 / 1
// Execute: dotnet "804ac9de-f76e-4442-9efe-0f0a4d318be4.dll" --benchmarkName "CSharpBenchmarks.Array2AccessMethods.LinqAggregate" --job "Jit=RyuJit, Platform=X64, Server=True" --benchmarkId 3 in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\bin\Release\netcoreapp2.2
// BeforeAnythingElse

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotSupportedException: Collection was of a fixed size.
   at CSharpBenchmarks.CollectionAccessMethods`1..ctor(T data) in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\Benchmarks\CollectionAccessMethods.cs:line 18
   at BenchmarkDotNet.Autogenerated.Runnable_3..ctor() in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\804ac9de-f76e-4442-9efe-0f0a4d318be4.notcs:line 2125
   at BenchmarkDotNet.Autogenerated.Runnable_3.Run(IHost host, String benchmarkName) in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\804ac9de-f76e-4442-9efe-0f0a4d318be4.notcs:line 2071
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\804ac9de-f76e-4442-9efe-0f0a4d318be4.notcs:line 54
// AfterAll
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!


// **************************
// Benchmark: Array2AccessMethods.LinqSum: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
// *** Execute ***
// Launch: 1 / 1
// Execute: dotnet "804ac9de-f76e-4442-9efe-0f0a4d318be4.dll" --benchmarkName "CSharpBenchmarks.Array2AccessMethods.LinqSum" --job "Jit=RyuJit, Platform=X64, Server=True" --benchmarkId 4 in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\bin\Release\netcoreapp2.2
// BeforeAnythingElse

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotSupportedException: Collection was of a fixed size.
   at CSharpBenchmarks.CollectionAccessMethods`1..ctor(T data) in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\Benchmarks\CollectionAccessMethods.cs:line 18
   at BenchmarkDotNet.Autogenerated.Runnable_4..ctor() in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\804ac9de-f76e-4442-9efe-0f0a4d318be4.notcs:line 2771
   at BenchmarkDotNet.Autogenerated.Runnable_4.Run(IHost host, String benchmarkName) in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\804ac9de-f76e-4442-9efe-0f0a4d318be4.notcs:line 2717
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\804ac9de-f76e-4442-9efe-0f0a4d318be4.notcs:line 54
// AfterAll
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!


// **************************
// Benchmark: Array2AccessMethods.LinqAll: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
// *** Execute ***
// Launch: 1 / 1
// Execute: dotnet "804ac9de-f76e-4442-9efe-0f0a4d318be4.dll" --benchmarkName "CSharpBenchmarks.Array2AccessMethods.LinqAll" --job "Jit=RyuJit, Platform=X64, Server=True" --benchmarkId 5 in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\bin\Release\netcoreapp2.2
// BeforeAnythingElse

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotSupportedException: Collection was of a fixed size.
   at CSharpBenchmarks.CollectionAccessMethods`1..ctor(T data) in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\Benchmarks\CollectionAccessMethods.cs:line 18
   at BenchmarkDotNet.Autogenerated.Runnable_5..ctor() in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\804ac9de-f76e-4442-9efe-0f0a4d318be4.notcs:line 3417
   at BenchmarkDotNet.Autogenerated.Runnable_5.Run(IHost host, String benchmarkName) in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\804ac9de-f76e-4442-9efe-0f0a4d318be4.notcs:line 3363
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\804ac9de-f76e-4442-9efe-0f0a4d318be4.notcs:line 54
// AfterAll
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!


// **************************
// Benchmark: Array2AccessMethods.LinqAny: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
// *** Execute ***
// Launch: 1 / 1
// Execute: dotnet "804ac9de-f76e-4442-9efe-0f0a4d318be4.dll" --benchmarkName "CSharpBenchmarks.Array2AccessMethods.LinqAny" --job "Jit=RyuJit, Platform=X64, Server=True" --benchmarkId 6 in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\bin\Release\netcoreapp2.2
// BeforeAnythingElse

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotSupportedException: Collection was of a fixed size.
   at CSharpBenchmarks.CollectionAccessMethods`1..ctor(T data) in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\Benchmarks\CollectionAccessMethods.cs:line 18
   at BenchmarkDotNet.Autogenerated.Runnable_6..ctor() in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\804ac9de-f76e-4442-9efe-0f0a4d318be4.notcs:line 4063
   at BenchmarkDotNet.Autogenerated.Runnable_6.Run(IHost host, String benchmarkName) in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\804ac9de-f76e-4442-9efe-0f0a4d318be4.notcs:line 4009
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\bin\Release\netcoreapp2.2\804ac9de-f76e-4442-9efe-0f0a4d318be4\804ac9de-f76e-4442-9efe-0f0a4d318be4.notcs:line 54
// AfterAll
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!


Successfully reverted power plan (GUID: 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c FriendlyName: High performance)
// ***** BenchmarkRunner: Finish  *****

// * Export *
Could not overwrite file E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\BenchmarkDotNet.Artifacts\results\CSharpBenchmarks.Array2AccessMethods-report.csv. Exporting to E:\git\benchmarks\CSharpBenchmarks\CSharpBenchmarks\BenchmarkDotNet.Artifacts\results\CSharpBenchmarks.Array2AccessMethods-report-20190413-230457.csv
  BenchmarkDotNet.Artifacts\results\CSharpBenchmarks.Array2AccessMethods-report-20190413-230457.csv
  BenchmarkDotNet.Artifacts\results\CSharpBenchmarks.Array2AccessMethods-report-github.md
  BenchmarkDotNet.Artifacts\results\CSharpBenchmarks.Array2AccessMethods-report.html
  BenchmarkDotNet.Artifacts\results\CSharpBenchmarks.Array2AccessMethods-report.txt

// * Detailed results *
Array2AccessMethods.ForCacheArray: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
Runtime = ; GC = 
There are not any results runs

Array2AccessMethods.For: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
Runtime = ; GC = 
There are not any results runs

Array2AccessMethods.ForEach: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
Runtime = ; GC = 
There are not any results runs

Array2AccessMethods.LinqAggregate: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
Runtime = ; GC = 
There are not any results runs

Array2AccessMethods.LinqSum: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
Runtime = ; GC = 
There are not any results runs

Array2AccessMethods.LinqAll: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
Runtime = ; GC = 
There are not any results runs

Array2AccessMethods.LinqAny: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
Runtime = ; GC = 
There are not any results runs

// * Summary *

BenchmarkDotNet=v0.11.5, OS=Windows 10.0.17134.706 (1803/April2018Update/Redstone4)
Intel Core i7-5820K CPU 3.30GHz (Broadwell), 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=2.2.105
  [Host] : .NET Core 2.2.3 (CoreCLR 4.6.27414.05, CoreFX 4.6.27414.05), 64bit RyuJIT

Jit=RyuJit  Platform=X64  Server=True  

|        Method | Mean | Error | Ratio | RatioSD |
|-------------- |-----:|------:|------:|--------:|
| ForCacheArray |   NA |    NA |     ? |       ? |
|           For |   NA |    NA |     ? |       ? |
|       ForEach |   NA |    NA |     ? |       ? |
| LinqAggregate |   NA |    NA |     ? |       ? |
|       LinqSum |   NA |    NA |     ? |       ? |
|       LinqAll |   NA |    NA |     ? |       ? |
|       LinqAny |   NA |    NA |     ? |       ? |

Benchmarks with issues:
  Array2AccessMethods.ForCacheArray: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
  Array2AccessMethods.For: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
  Array2AccessMethods.ForEach: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
  Array2AccessMethods.LinqAggregate: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
  Array2AccessMethods.LinqSum: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
  Array2AccessMethods.LinqAll: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)
  Array2AccessMethods.LinqAny: Job-LSBXGT(Jit=RyuJit, Platform=X64, Server=True)

// * Warnings *
Environment
  Summary -> Detected error exit code from one of the benchmarks. It might be caused by following antivirus software:
        - Windows Defender (windowsdefender://)
Use InProcessToolchain to avoid new process creation.


// * Legends *
  Mean    : Arithmetic mean of all measurements
  Error   : Half of 99.9% confidence interval
  Ratio   : Mean of the ratio distribution ([Current]/[Baseline])
  RatioSD : Standard deviation of the ratio distribution ([Current]/[Baseline])
  1 ns    : 1 Nanosecond (0.000000001 sec)

// ***** BenchmarkRunner: End *****
// ** Remained 0 benchmark(s) to run **
Run time: 00:00:01 (1.59 sec), executed benchmarks: 7

Global total time: 00:00:07 (7.11 sec), executed benchmarks: 7
// * Artifacts cleanup *
